export enum EPageRoute {
  CREATE = 'create',
  UPDATE = 'update',
  LOGIN = 'login',
  DASHBOARD = 'dashboard',
  JOB_POSITION = 'job-position',
  RECOMMEND_JOB_POSITION = 'recommend-job-position',
  RECOMMEND_JOB_POSITION_TO_AGENCY = 'recommend-job-position-to-agency',
  JOB_APPLICANT_INTERNSHIP = 'job-applicant-internship',
  HOME_MANAGEMENT = 'home-management',
  HOME_MANAGEMENT_POPUP_IMAGE = 'popup-image',
  HOME_MANAGEMENT_ANNOUNCEMENT = 'announcement',
  HOME_MANAGEMENT_MAIN_SLIDE_IMAGE = 'main-slide-image',
  HOME_MANAGEMENT_PHOTO_OF_ELECTRIC_TRAIN = 'photo-of-electric-train',
  HOME_MANAGEMENT_CORPORATE_CULTURE = 'corporate-culture',
  INTERNSHIP_PAGE_CONTENT = 'internship-page-content',
  EMPLOYEE_ACTIVITY_PAGE_CONTENT = 'employee-activity-page-content',
  WELFARE_PAGE_CONTENT = 'welfare-page-content',
  OTHER_PAGE_CONTENT = 'other-page-content',
  MANGE_OTHER_PAGE_CONTENT = 'manage-other-page-content',
  ROLE = 'role',
  USER = 'user',
  MASTER_INFORMATION = 'master-information',
  UNKNOWN = 'page-not-found',
}
